# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0007_auto_20170208_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pi',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
