# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0011_pi_manual_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='lower_threshold',
            new_name='residual_threshold',
        ),
        migrations.RemoveField(
            model_name='device',
            name='upper_threshold',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='bio_threshold',
            field=models.FloatField(blank=True, null=True, verbose_name='Biological Threshold'),
        ),
    ]
