# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Type',
            new_name='DataType',
        ),
        migrations.RenameModel(
            old_name='Device_Type',
            new_name='DeviceType',
        ),
        migrations.RenameModel(
            old_name='Unit_Type',
            new_name='UnitType',
        ),
    ]
