# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0002_auto_20170206_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
