# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0009_remove_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
