# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0010_auto_20170208_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='manual_control',
            field=models.BooleanField(default=False),
        ),
    ]
