# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0012_auto_20170227_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_on', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('executed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='bio_threshold',
            field=models.FloatField(default=0.0, verbose_name='Biological Threshold'),
        ),
        migrations.AddField(
            model_name='controllerupdate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Updates', to='foodcomputer.Device'),
        ),
    ]
