# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0013_auto_20170325_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='max_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='min_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controllerupdate',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 15, 19, 59, 5, 21983)),
        ),
    ]
