# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0013_auto_20170325_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittype',
            name='max_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='min_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
