# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0014_auto_20170411_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='min_limit',
        ),
        migrations.AddField(
            model_name='unittype',
            name='max_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='min_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
