# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomputer', '0015_moveMinMaxLimitsFields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='max_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datatype',
            name='min_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
